### ISSUE TITLE
unrecognizable data type

### ISSUE THREAD

**Issue by yaboibutt3r** [BryceCanyonCounty/bcc-saloons#10]
`id` uuid NOT NULL, urecognizable near uuid

**Comment by Fistsofury** [comment]
You need to upgrade your version of MariaDB to something like 10.11 and above

> `id` uuid NOT NULL, urecognizable near uuid

**Comment by yaboibutt3r** [comment]
silly me I am using phpadmin cause the servers through zap... thanks for the clarification
